provisioner:
  name: chef_zero
  chef_omnibus_url: http://www.getchef.com/chef/install.sh
  require_chef_omnibus: 12.11.18

platforms:
- name: ubuntu
  driver:
    name: vagrant
    box: ubuntu/trusty64
    gui: true
  #attributes:

suites:
  - name: mediaserver
    driver:
      customize:
        memory: '4000'
        cpus: '2'
    run_list:
        - recipe[mediaserver]
    attributes:
      mediaserver:
        sources:
          video_sources:
            - name: "Movies"
              path: "smb://192.168.0.4/Movies"
              allowsharing: true
            - name: "Episodes"
              path: "smb://192.168.0.4/Episodes"
              allowsharing: true
        advancedsettings:
          videodatabase:
            type: "mysql"
            host: "192.168.0.4"
            port: 3306
            user: "kodi"
            pass: "kodi"
