name 'mediaserver'
maintainer 'Tyghe Vallard'
maintainer_email 'vallardt@gmail.com'
license 'all_rights'
description 'Setup home media server'
version '0.2.0'
issues_url 'https://github.com/necrolyte2/mediaserver/issues'
source_url 'https://github.com/necrolyte2/mediaserver'

depends 'kodi', '~> 0.1.4'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'mysql', '~> 7.0'
depends 'database', '~> 5.1.2'

supports 'ubuntu'
